#!/usr/bin/env ts-node

/**
 * Interactive setup wizard - helps users configure .env file
 */

import * as fs from 'fs';
import * as readline from 'readline';

const colors = {
    reset: '\x1b[0m',
    bright: '\x1b[1m',
    green: '\x1b[32m',
    yellow: '\x1b[33m',
    cyan: '\x1b[36m',
};

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

const ask = (question: string, defaultVal = ''): Promise<string> =>
    new Promise((resolve) => {
        const prompt = defaultVal
            ? `${colors.cyan}${question}${colors.reset} [${defaultVal}]: `
            : `${colors.cyan}${question}${colors.reset}: `;
        rl.question(prompt, (answer) => resolve(answer.trim() || defaultVal));
    });

async function main() {
    console.log(`\n${colors.bright}${colors.green}━━━ Polymarket Copy Bot - Setup Wizard ━━━${colors.reset}\n`);

    const envPath = '.env';
    if (fs.existsSync(envPath)) {
        const overwrite = await ask('Existing .env found. Overwrite? (y/n)', 'n');
        if (overwrite.toLowerCase() !== 'y') {
            console.log(`\n${colors.yellow}Skipped. Edit .env manually if needed.${colors.reset}\n`);
            rl.close();
            return;
        }
    }

    console.log(`\n${colors.yellow}Step 1: Traders to copy${colors.reset}`);
    console.log('  Find addresses at https://polymarket.com/leaderboard\n');
    const userAddresses = await ask(
        'Traders (comma-separated, e.g. 0xABC...,0xDEF...)',
        '0x6a72f61820b26b1fe4d956e17b6dc2a1ea3033ee'
    );

    console.log(`\n${colors.yellow}Step 2: Your wallet${colors.reset}`);
    const proxyWallet = await ask('Your Polygon wallet address (PROXY_WALLET)');
    const privateKey = await ask('Private key (WITHOUT 0x prefix)');

    console.log(`\n${colors.yellow}Step 3: Database${colors.reset}`);
    console.log('  Free MongoDB at https://mongodb.com/cloud/atlas\n');
    const mongoUri = await ask(
        'MongoDB URI',
        'mongodb+srv://user:pass@cluster.mongodb.net/?appName=Cluster0'
    );

    console.log(`\n${colors.yellow}Step 4: Polygon RPC${colors.reset}`);
    console.log('  Free at https://infura.io or https://alchemy.com\n');
    const rpcUrl = await ask(
        'RPC URL',
        'https://polygon-mainnet.infura.io/v3/YOUR_PROJECT_ID'
    );

    const content = `# Polymarket Copy Bot - Generated by setup wizard
USER_ADDRESSES='${userAddresses.replace(/'/g, "\\'")}'
PROXY_WALLET='${proxyWallet}'
PRIVATE_KEY='${privateKey}'

CLOB_HTTP_URL='https://clob.polymarket.com/'
CLOB_WS_URL='wss://ws-subscriptions-clob.polymarket.com/ws'

FETCH_INTERVAL=1
TOO_OLD_TIMESTAMP=24
RETRY_LIMIT=3
EXECUTOR_INTERVAL_MS=300

COPY_STRATEGY=PERCENTAGE
COPY_SIZE=10.0
MAX_ORDER_SIZE_USD=100.0
MIN_ORDER_SIZE_USD=1.0

TRADE_AGGREGATION_ENABLED=false
TRADE_AGGREGATION_WINDOW_SECONDS=300

MONGO_URI='${mongoUri}'
RPC_URL='${rpcUrl}'
USDC_CONTRACT_ADDRESS='0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174'
`;

    fs.writeFileSync(envPath, content, 'utf8');
    console.log(`\n${colors.green}✓ .env created successfully!${colors.reset}`);
    console.log(`\nNext steps:`);
    console.log(`  1. ${colors.cyan}npm run health-check${colors.reset}  Verify config`);
    console.log(`  2. ${colors.cyan}npm run build${colors.reset}        Compile`);
    console.log(`  3. ${colors.cyan}npm start${colors.reset}            Start trading\n`);
    rl.close();
}

main().catch((err) => {
    console.error(err);
    rl.close();
    process.exit(1);
});
